name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pacman Graph
        uses: yoshi389111/github-contribution-graph-generator@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: ./output/pacman-contribution-graph.svg
          output_path_dark: ./output/pacman-contribution-graph-dark.svg
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.svg
          git commit -m "Update Pacman Contribution Graph"
          git push
