name: Pac-Man Contributions
on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza diariamente
  workflow_dispatch:     # Acionamento manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Pac-Man Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_pacman: yes
          plugin_pacman_commit: yes
          output: output/pacman-contribution-graph.svg
